[package]
name = "xenon-browser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.7.2"
libadwaita = "0.5.2"
webrender = "0.61.0"
